name: Deploy GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@main
        with:
          persist-credentials: false
          fetch-depth: 0 
      - name: Setup Node  🎬
        uses: actions/setup-node@main
        with:
          node-version: "lts/*"
      - name: Build 🔧 
        run: |
          npm install
          npm run build
          ls -lrth
      - name: Deploy 🚀 
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.TOKEN_TW }} 
          branch: gh-pages
          folder: dist